version: "3.9"
services:
  mysqldb:
    image: mysql:8.0.27
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "3306:3306"

  app:
    container_name: app
    env_file:
      - .env
    build:
      dockerfile: Dockerfile 
    image: myappimage
    ports:
      - "3000:3000"
    depends_on:
      - mysqldb

  
