version: "3.9"
services:
  mysqldb:
    image: mysql:8.0.27
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - "./src/config/mysql/scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./src/config/mysql/scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./src/config/mysql/scripts/mycustom.cnf:/etc/mysql/conf.d/custom.cnf"
    ports:
      - "3306:3306"

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD} #see .env file for environment variable ${REDIS_PASSWORD}

  app:
    container_name: app
    restart: always
    env_file:
      - .env
    build:
      dockerfile: Dockerfile 
    image: myappimage
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - "./src:/usr/src/app/src"
      - "./logs:/usr/src/app/logs"
    depends_on:
      - mysqldb
      - redis

  
